# Generated by Django 4.1.3 on 2022-11-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='anons',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='full_text',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='image',
        ),
        migrations.AddField(
            model_name='articles',
            name='imageBlog',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
