# Generated by Django 4.1.3 on 2022-11-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_articles_imageblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='imageBlog',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
